a1 = float(input("Enter first number (a) = "))
b1 = float(input("Enter second number (b) = "))
print("Addition = ", a + b)
print("Subtraction = ", a - b)
print("Multiplication = ", a * b)
print("Division = ", a / b if b != 0 else "Cannot divide by zero")
